### ISSUE TITLE
toutsurmoneau.errors.ClientError: Failed refreshing cookie

### ISSUE THREAD

**Issue by lraulet** [laurent-martin/py-mon-eau#1]
Bonjour,
Tentant d'ajouter l'intégration dans HomeAssistant, j'ai une erreur "Unexpected Error".
Du coup, j'ai voulu tester directement py-mon-eau en ligne de commande sur une Ubuntu 22.04 (WSL)

MonPC:~$ toutsurmoneau -u MonEmail -p MonPassword -c MonCompteur
true
...

Donc l'authentification semble OK.
Par contre si je tente de récupérer la consommation, j'ai une erreur de refresh cookie

MonPC:~$ toutsurmoneau -u MonEmail  -p MonPassword -c MonCompteur -U https://www.seop.fr -e daily_for_month
Traceback (most recent call last):
  File "/home/lraulet/.local/bin/toutsurmoneau", line 8, in <module>
    sys.exit(command_line())
  File "/home/lraulet/.local/lib/python3.10/site-packages/toutsurmoneau/__main__.py", line 37, in command_line
    result = asyncio.run(async_execute(args))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/lraulet/.local/lib/python3.10/site-packages/toutsurmoneau/__main__.py", line 94, in async_execute
    data = await client.async_daily_for_month(test_date)
  File "/home/lraulet/.local/lib/python3.10/site-packages/toutsurmoneau/async_client.py", line 258, in async_daily_for_month
    daily = await self._async_call_api(
  File "/home/lraulet/.local/lib/python3.10/site-packages/toutsurmoneau/async_client.py", line 211, in _async_call_api
    raise ClientError('Failed refreshing cookie')
toutsurmoneau.errors.ClientError: Failed refreshing cookie

A noter que la commande -e meter_id fonctionne

**Comment by lraulet** [comment]
@laurent-martin , N'hésitez pas à me dire si vous avez besoin de plus d'info ou bien que je fasse des tests supplémentaires.

**Comment by lraulet** [comment]
@laurent-martin 
Je pense avoir trouvé le problème mais je ne suis pas expert en Python ; donc il y a peut être des choses que j'ai raté.
Le faite de spécifier le provider avec l'option -u n'est pas prise en compte correctement dans la fonction __init__() de la classe AsyncClient.
[Ici](https://github.com/laurent-martin/py-mon-eau/blob/6445d7d9ad5d72f8d9dd5f7bf765d6c3931173da/toutsurmoneau/async_client.py#L66), Ligne 66 du fichier async_client.py vous faites un : 
self._api_base_url = KNOWN_PROVIDER_URLS[0]
Du coup, l'URL de base n'est pas correcte lorsqu'on n'utilise pas le provider toutsurmoneau.fr. En effet lorsqu'on spécifie un autre provider, le _provider_url sera correct mais pas le champ _api_base_url qui lui sera toujours à toutsurmoneau.fr. Du coup, la session créée pour le provider spécifique (seop.fr dans mon cas) est refusée lorsqu'on tente les autres appels sur le domaine toutsurmoneau.fr
En changeant simplement par : 
self._api_base_url = self._provider_url
cela fonctionne comme attendu de mon coté.

Vous est-il possible de pousser un fix et de mettre à jour l'intégration homeassistant s'il vous plait ?
Ou bien m'expliquer comme le faire manuellement de mon coté pour me débloquer.

**Comment by laurent-martin** [comment]
Ca y est j'ai poussé une version

**Comment by lraulet** [comment]
Merci @laurent-martin , la version 0.0.24 corrige bien le problème mais il y a un bug bloquant : https://github.com/laurent-martin/py-mon-eau/issues/3
J'ai donc du modifier le fichier async_client.py pour vérifier la correction du bug actuel.

**Comment by lraulet** [comment]
Je confirme que c'est OK avec la version 0.0.25
