### ISSUE TITLE
Provider URL non pris en compte pour le cas "donnees-contrats"

### ISSUE THREAD

**Issue by lraulet** [laurent-martin/py-mon-eau#2]
Pour le cas "donnees-contrats" le provider URL n'est pas pris en compte. Du coup, c'est l'url https://www.toutsurmoneau.fr/public-api/user qui est utilisée.
https://github.com/laurent-martin/py-mon-eau/blob/6445d7d9ad5d72f8d9dd5f7bf765d6c3931173da/toutsurmoneau/async_client.py#L76

**Comment by laurent-martin** [comment]
Oui,... en fait je testais avec www.toutsurmoneau.com
Puis le fournisseur local a change (toujours suez) et mon compte etait resilié, difficile de tester.
Et depuis quelques jours c'est revenu ... sur le nouveau fournisseur d'eau local, So'eau.
La derniere version fonctionne ainsi.

**Comment by lraulet** [comment]
Merci @laurent-martin , la version 0.0.24 corrige bien le problème mais il y a un bug bloquant : https://github.com/laurent-martin/py-mon-eau/issues/3
J'ai donc du modifier le fichier async_client.py pour vérifier la correction du bug actuel.

De mon coté, la SEOP a dû changer un truc car je n'ai plus accès à mes relevés sur leur site web. Par contre par l'API je peux encore récupérer les infos jusqu'au 17 Mars. Du coup, je peux tout de même valider/vérifier les corrections de bugs.

**Comment by laurent-martin** [comment]
J'ai mis a jour le module py-mon-eau, mais pas encore l'integration...

**Comment by lraulet** [comment]
Je confirme que c'est OK avec la version 0.0.25
Ne manque plus que la mise à jour de la dépendance dans l'intégration.
