### ISSUE TITLE
Problème de retour chariot sur version 0.0.24

### ISSUE THREAD

**Issue by lraulet** [laurent-martin/py-mon-eau#3]
Je viens d'installer la version 0.0.24, je pense qu'il y a un problème de retour chariot ligne 185 du fichier assync_client.py
En effet un appel à toutsurmonreseau (sans autre paramètre) donne ceci : 

test@SurfaceBook~/.local/bin$ ./toutsurmoneau
Traceback (most recent call last):
  File "/home/test/.local/bin/./toutsurmoneau", line 5, in <module>
    from toutsurmoneau.__main__ import command_line
  File "/home/test/.local/lib/python3.10/site-packages/toutsurmoneau/__init__.py", line 2, in <module>
    from .client import Client
  File "/home/test/.local/lib/python3.10/site-packages/toutsurmoneau/client.py", line 6, in <module>
    from .async_client import AsyncClient
  File "/home/test/.local/lib/python3.10/site-packages/toutsurmoneau/async_client.py", line 185
    _LOGGER.debug(f"Redirected to {
                  ^
SyntaxError: unterminated string literal (detected at line 185)

En remplaçant : 
                _LOGGER.debug(f"Redirected to {
                              PAGE_LOGIN}, performing login...")

par
                _LOGGER.debug(f"Redirected to {PAGE_LOGIN}, performing login...")

Cela fonctionne correctement
test@SurfaceBook:~/.local/bin$ ./toutsurmoneau
usage: toutsurmoneau [-h] -u USERNAME -p PASSWORD [-c METER_ID] [-U URL] [-e EXECUTE] [-d DATA] [--debug] [--legacy]
toutsurmoneau: error: the following arguments are required: -u/--username, -p/--password

**Comment by laurent-martin** [comment]
Oui, probleme introduit par le formatteur automatique autopep8,. .. J'ai modifié les parametres pour eviter le probleme...

**Comment by lraulet** [comment]
Merci.
Je confirme que c'est ok avec la version 0.0.25
